# Generated by Django 5.2 on 2025-05-07 13:48

import parking.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0002_parkinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryexitlog",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="entryexitlog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=parking.models.entry_image_upload_path
            ),
        ),
        migrations.AddConstraint(
            model_name="entryexitlog",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "is_open"), name="unique_open_log_per_vehicle"
            ),
        ),
    ]
