# Generated by Django 5.2 on 2025-05-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_entryexitlog_is_open_alter_entryexitlog_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('license_plate',)},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
    ]
